# Generated by Django 3.1.5 on 2021-02-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'others')])),
                ('occupation', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
