# Generated by Django 3.1.5 on 2021-02-02 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210202_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Test'),
        ),
    ]
