# Generated by Django 3.1.5 on 2021-02-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210204_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='UserIncome',
        ),
    ]
