# Generated by Django 3.1.5 on 2021-02-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
    ]
