# Generated by Django 3.1.5 on 2021-02-05 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0006_category_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category1',
        ),
    ]
