# Generated by Django 3.1.5 on 2021-02-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_categorylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylist',
            old_name='owner',
            new_name='user',
        ),
    ]
