# Generated by Django 3.1.5 on 2021-02-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_auto_20210205_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='categorylist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='CategoryList',
        ),
    ]
